module
public import Solution

#print axioms Gershkov.feasible_entry_le_one
#print axioms Gershkov.feasible_isClosed
#print axioms Gershkov.slope_continuous
#print axioms Gershkov.alternative_continuous
#print axioms Gershkov.matches_isClosed
#print axioms Gershkov.matches_isCompact
#print axioms Gershkov.energy_continuous
#print axioms Gershkov.exists_minimizer
#print axioms Gershkov.transfers_for_matching_allocation
#print axioms Gershkov.finite_bayesian_dominant_equivalence
#print axioms Gershkov.Examples.types
#print axioms Gershkov.Examples.firstPrior
#print axioms Gershkov.Examples.secondPrior
#print axioms Gershkov.Examples.original
#print axioms Gershkov.Examples.lifted
#print axioms Gershkov.Examples.firstSlope
#print axioms Gershkov.Examples.secondSlope
#print axioms Gershkov.Examples.firstTransfer
#print axioms Gershkov.Examples.secondTransfer
#print axioms Gershkov.Examples.allocation
#print axioms Gershkov.Examples.priors_positive_normalized
#print axioms Gershkov.Examples.types_strictMono
#print axioms Gershkov.Examples.allocations_feasible
#print axioms Gershkov.Examples.weighted_marginals
#print axioms Gershkov.Examples.original_bic
#print axioms Gershkov.Examples.original_not_dic
#print axioms Gershkov.Examples.lifted_dic
#print axioms Gershkov.Examples.exAnte_on_probability
#print axioms Gershkov.Examples.constantSurplus
#print axioms Gershkov.Examples.nonzero_constants_surplus
#print axioms Gershkov.Examples.interim_utilities_equal
#print axioms Gershkov.Examples.flat_coefficient
#print axioms Gershkov.Examples.negativeTypes
#print axioms Gershkov.Examples.negative_types_ic
#print axioms Gershkov.Examples.singleton_transfer
#print axioms Gershkov.crossing_context
#print axioms Gershkov.improving_perturbation
#print axioms Gershkov.minimizer_monotone
#print axioms Gershkov.weighted_monotone_lifting
#print axioms Gershkov.Types
#print axioms Gershkov.modified
#print axioms Gershkov.payoff
#print axioms Gershkov.interimPayoff
#print axioms Gershkov.BIC
#print axioms Gershkov.DIC
#print axioms Gershkov.modifiedInterim
#print axioms Gershkov.payoff_modified
#print axioms Gershkov.interimPayoff_modified
#print axioms Gershkov.bic_scalar
#print axioms Gershkov.socialSurplus
#print axioms Gershkov.exAnte_value
#print axioms Gershkov.exAnte_typeValue
#print axioms Gershkov.surplus_matches
#print axioms Gershkov.exAnte_transfers_match
#print axioms Gershkov.Profile
#print axioms Gershkov.Opponents
#print axioms Gershkov.pack
#print axioms Gershkov.pack_self
#print axioms Gershkov.pack_other
#print axioms Gershkov.pack_split
#print axioms Gershkov.pack_injective
#print axioms Gershkov.joint
#print axioms Gershkov.opponentMass
#print axioms Gershkov.SupportPrior
#print axioms Gershkov.joint_pos
#print axioms Gershkov.opponentMass_pos
#print axioms Gershkov.joint_pack
#print axioms Gershkov.joint_sum
#print axioms Gershkov.opponentMass_sum
#print axioms Gershkov.interim
#print axioms Gershkov.exAnte
#print axioms Gershkov.fiber_moment
#print axioms Gershkov.exAnte_interim
#print axioms Gershkov.interim_const
#print axioms Gershkov.interim_add
#print axioms Gershkov.interim_sub
#print axioms Gershkov.interim_mul
#print axioms Gershkov.slope
#print axioms Gershkov.Matches
#print axioms Gershkov.value
#print axioms Gershkov.Feasible
#print axioms Gershkov.energy
#print axioms Gershkov.mixPair
#print axioms Gershkov.sum_change_two
#print axioms Gershkov.mixPair_left
#print axioms Gershkov.mixPair_right
#print axioms Gershkov.mixPair_other
#print axioms Gershkov.value_mixPair_left
#print axioms Gershkov.value_mixPair_right
#print axioms Gershkov.mixPair_feasible
#print axioms Gershkov.mixPair_moment
#print axioms Gershkov.mixPair_energy
#print axioms Gershkov.mixPair_energy_lt
#print axioms Gershkov.doubleMix
#print axioms Gershkov.doubleMix_moment
#print axioms Gershkov.doubleMix_energy_lt
#print axioms Gershkov.PositiveSupport
#print axioms Gershkov.positiveSupportFintype
#print axioms Gershkov.positiveSupportDecidableEq
#print axioms Gershkov.expectation_on_support
#print axioms Gershkov.support_normalized
#print axioms Gershkov.support_nonempty
#print axioms Gershkov.product_expectation_on_support
#print axioms Gershkov.opponent_expectation_on_support
#print axioms Gershkov.Transfers.ScalarIC
#print axioms Gershkov.Transfers.AdjacentIC
#print axioms Gershkov.Transfers.adjacent_of_ic
#print axioms Gershkov.Transfers.monotone_of_ic
#print axioms Gershkov.Transfers.coefficient
#print axioms Gershkov.Transfers.coefficient_bounds
#print axioms Gershkov.Transfers.coefficient_transfer_delta
#print axioms Gershkov.Transfers.pair_bounds_of_adjacent
#print axioms Gershkov.Transfers.ic_of_adjacent
#print axioms Gershkov.Transfers.scalarIC_iff_monotone_adjacent
#print axioms Gershkov.Transfers.edge
#print axioms Gershkov.Transfers.transfer
#print axioms Gershkov.Transfers.transfer_zero
#print axioms Gershkov.Transfers.Iio_succ_eq_insert
#print axioms Gershkov.Transfers.transfer_adjacent_delta
#print axioms Gershkov.Transfers.constructed_transfer_ic
#print axioms Gershkov.Transfers.mean
#print axioms Gershkov.Transfers.mean_sub
#print axioms Gershkov.Transfers.mean_mul
#print axioms Gershkov.Transfers.mean_const
#print axioms Gershkov.Transfers.constructed_transfer_mean
#print axioms Gershkov.Transfers.modified_transfer_exists
#print axioms GGKMS.value
#print axioms GGKMS.Feasible
#print axioms GGKMS.energy
#print axioms GGKMS.Profile
#print axioms GGKMS.Opponents
#print axioms GGKMS.pack
#print axioms GGKMS.joint
#print axioms GGKMS.opponentMass
#print axioms GGKMS.SupportPrior
#print axioms GGKMS.interim
#print axioms GGKMS.exAnte
#print axioms GGKMS.slope
#print axioms GGKMS.Matches
#print axioms GGKMS.Types
#print axioms GGKMS.modified
#print axioms GGKMS.payoff
#print axioms GGKMS.interimPayoff
#print axioms GGKMS.BIC
#print axioms GGKMS.DIC
#print axioms GGKMS.modifiedInterim
#print axioms GGKMS.socialSurplus
#print axioms GGKMS.Transfers.ScalarIC
#print axioms GGKMS.Transfers.AdjacentIC
#print axioms GGKMS.PositiveSupport
#print axioms GGKMS.positiveSupportFintype
#print axioms GGKMS.positiveSupportDecidableEq
#print axioms GGKMS.finite_bayesian_dominant_equivalence
#print axioms GGKMS.weighted_monotone_lifting
#print axioms GGKMS.minimizer_monotone
#print axioms GGKMS.Transfers.scalarIC_iff_monotone_adjacent
#print axioms GGKMS.expectation_on_support
#print axioms GGKMS.product_expectation_on_support
