module
public import Challenge

set_option pp.explicit true
#check @GGKMS.finite_bayesian_dominant_equivalence
#print GGKMS.finite_bayesian_dominant_equivalence
#check @GGKMS.weighted_monotone_lifting
#print GGKMS.weighted_monotone_lifting
#check @GGKMS.minimizer_monotone
#print GGKMS.minimizer_monotone
#check @GGKMS.Transfers.scalarIC_iff_monotone_adjacent
#print GGKMS.Transfers.scalarIC_iff_monotone_adjacent
#check @GGKMS.expectation_on_support
#print GGKMS.expectation_on_support
#check @GGKMS.product_expectation_on_support
#print GGKMS.product_expectation_on_support
#check @GGKMS.value
#print GGKMS.value
#check @GGKMS.Feasible
#print GGKMS.Feasible
#check @GGKMS.energy
#print GGKMS.energy
#check @GGKMS.Profile
#print GGKMS.Profile
#check @GGKMS.Opponents
#print GGKMS.Opponents
#check @GGKMS.pack
#print GGKMS.pack
#check @GGKMS.joint
#print GGKMS.joint
#check @GGKMS.opponentMass
#print GGKMS.opponentMass
#check @GGKMS.SupportPrior
#print GGKMS.SupportPrior
#check @GGKMS.interim
#print GGKMS.interim
#check @GGKMS.exAnte
#print GGKMS.exAnte
#check @GGKMS.slope
#print GGKMS.slope
#check @GGKMS.Matches
#print GGKMS.Matches
#check @GGKMS.Types
#print GGKMS.Types
#check @GGKMS.modified
#print GGKMS.modified
#check @GGKMS.payoff
#print GGKMS.payoff
#check @GGKMS.interimPayoff
#print GGKMS.interimPayoff
#check @GGKMS.BIC
#print GGKMS.BIC
#check @GGKMS.DIC
#print GGKMS.DIC
#check @GGKMS.modifiedInterim
#print GGKMS.modifiedInterim
#check @GGKMS.socialSurplus
#print GGKMS.socialSurplus
#check @GGKMS.Transfers.ScalarIC
#print GGKMS.Transfers.ScalarIC
#check @GGKMS.Transfers.AdjacentIC
#print GGKMS.Transfers.AdjacentIC
#check @GGKMS.PositiveSupport
#print GGKMS.PositiveSupport
#check @GGKMS.positiveSupportFintype
#print GGKMS.positiveSupportFintype
#check @GGKMS.positiveSupportDecidableEq
#print GGKMS.positiveSupportDecidableEq
